<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mderl" nsURI="http://www.example.org/mderl" nsPrefix="mderl">
  <eClassifiers xsi:type="ecore:EClass" name="Experiment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;experiment&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//config" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agent" lowerBound="1" upperBound="-1"
        eType="#//Agent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        upperBound="-1" eType="#//Environment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="robotcomponent" lowerBound="1"
        eType="#//RobotComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" upperBound="-1"
        eType="#//Model" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scene" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="config"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mobile" abstract="true" eSuperTypes="#//RobotComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dummy" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arm" abstract="true" eSuperTypes="#//Fixed"/>
  <eClassifiers xsi:type="ecore:EClass" name="RobotComponent" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="joint_names" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Panda" eSuperTypes="#//Arm"/>
  <eClassifiers xsi:type="ecore:EClass" name="TurtleBot" eSuperTypes="#//WheeledRobot"/>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" lowerBound="1"
        upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" lowerBound="1"
        upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linear_velocity" upperBound="3"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angular_velocity" upperBound="3"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fixed" abstract="true" eSuperTypes="#//RobotComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="AerialRobot" abstract="true" eSuperTypes="#//Mobile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propeller_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WheeledRobot" abstract="true" eSuperTypes="#//Mobile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wheel_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ARDrone" eSuperTypes="#//AerialRobot"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RLKit" abstract="true" eSuperTypes="#//Model"/>
  <eClassifiers xsi:type="ecore:EClass" name="RLKSac" eSuperTypes="#//RLKit"/>
</ecore:EPackage>
