<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robot_learning" nsURI="http://www.example.org/robot_learning"
    nsPrefix="robot_learning">
  <eClassifiers xsi:type="ecore:EClass" name="Experiment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="agent" lowerBound="1" upperBound="-1"
        eType="#//Agent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//Environment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;experiment&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scene" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headless" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="True"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action_space" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observation_space" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responsible_ui" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocking" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" upperBound="-1"
        eType="#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replay_buffer" eType="#//ReplayBuffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RobotComponent" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="joint_names" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intermediate_target_base"
        eType="#//Dummy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target_base" eType="#//Dummy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" lowerBound="1"
        upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" lowerBound="1"
        upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linear_velocity" upperBound="3"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angular_velocity" upperBound="3"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dummy" eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model"/>
  <eClassifiers xsi:type="ecore:EClass" name="AerialRobot" abstract="true" eSuperTypes="#//Mobile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propeller_names" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mobile" abstract="true" eSuperTypes="#//RobotComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fixed" abstract="true" eSuperTypes="#//RobotComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="WheeledRobot" abstract="true" eSuperTypes="#//Mobile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wheel_names" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arm" abstract="true" eSuperTypes="#//Fixed"/>
  <eClassifiers xsi:type="ecore:EClass" name="SAC" eSuperTypes="#//ActorCritic"/>
  <eClassifiers xsi:type="ecore:EClass" name="PPO" eSuperTypes="#//ActorCritic"/>
  <eClassifiers xsi:type="ecore:EClass" name="NeuralNetwork"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActorCritic" eSuperTypes="#//Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PolicyNetwork" lowerBound="1"
        eType="#//NeuralNetwork" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ValueNetwork" lowerBound="1"
        upperBound="-1" eType="#//NeuralNetwork" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplayBuffer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ARDrone" eSuperTypes="#//AerialRobot"/>
  <eClassifiers xsi:type="ecore:EClass" name="Panda" eSuperTypes="#//Arm"/>
  <eClassifiers xsi:type="ecore:EClass" name="TurtleBot" eSuperTypes="#//WheeledRobot"/>
</ecore:EPackage>
